In [1]:
# Importing the necessary packages

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import re
import pandas as pd

In [2]:
data = pd.read_csv('tripadvisor_hotel_reviews.csv')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    str
 1   Rating  109 non-null    int64
dtypes: int64(1), str(1)
memory usage: 1.8 KB

In [3]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [4]:
data['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [5]:
# Convert text in the Review column to lowercase

review_lowercase = data['Review'].str.lower()

In [6]:
data['Review_lowercase'] = review_lowercase

In [7]:
data

,Review,Rating,Review_lowercase
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."
...,...,...,...
104,"fairmont hotel singapore splendid, stayed fair...",5,"fairmont hotel singapore splendid, stayed fair..."
105,great hotel stayed hotel night route perth chr...,4,great hotel stayed hotel night route perth chr...
106,great hotel centre stayed 5 nights room overlo...,4,great hotel centre stayed 5 nights room overlo...
107,great location great value great hotel husband...,5,great location great value great hotel husband...
108,lovely hotel great location stayed vacation to...,5,lovely hotel great location stayed vacation to...

In [8]:
# Create our English Stopwords list.

en_stopwords = stopwords.words('english')

In [9]:
en_stopwords.remove('not') #Decided to remove the 'not' word from our stopwords list

In [10]:
en_stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [11]:
# Extract words that are not present in stopwords

data['Review_no_stopwords'] = data['Review_lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))

In [12]:
data.head()

,Review,Rating,Review_lowercase,Review_no_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [13]:
data['Review_no_stopwords'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

# apply() function

It takes one columns and performs custom operation on every value in it

When we are preprocessing text, it is always worth making a new column for each of the steps in your preprocessing

In [14]:
# Remmoving Punctuations using Regular Expressions

data['Review_no_punc'] = data.apply(lambda x: re.sub(r"[*]", " star", x["Review_no_stopwords"]), axis=1)

In [15]:
data.head()

,Review,Rating,Review_lowercase,Review_no_stopwords,Review_no_punc
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4 star experience hotel monaco ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [16]:
data['Review_no_punc'] = data.apply(lambda x: re.sub(r"([^\w\s])", "", x["Review_no_punc"]), axis=1)

In [17]:
data.head()

,Review,Rating,Review_lowercase,Review_no_stopwords,Review_no_punc
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4 star experience hotel monaco ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...

In [18]:
# Tokenizing text using word_tokenize()

data['tokenized_review'] = data.apply(lambda x: word_tokenize(x['Review_no_punc']), axis=1)

In [19]:
data.head()

,Review,Rating,Review_lowercase,Review_no_stopwords,Review_no_punc,tokenized_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4 star experience hotel monaco ...,"[nice, rooms, not, 4, star, experience, hotel,..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

In [20]:
data['tokenized_review'][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'reviews',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillows',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bangs',
 'doors',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbors',
 'aveda',
 'bath',
 'products',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [21]:
# Stemming using PorterStemmer

ps = PorterStemmer()

In [22]:
data['stemmed_review'] = data['tokenized_review'].apply(lambda tokens: [ps.stem(token) for token in tokens])

In [23]:
data.head()

,Review,Rating,Review_lowercase,Review_no_stopwords,Review_no_punc,tokenized_review,stemmed_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4 star experience hotel monaco ...,"[nice, rooms, not, 4, star, experience, hotel,...","[nice, room, not, 4, star, experi, hotel, mona..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [24]:
#Lemmatizing the text using WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [25]:
data['lemmatized_review'] = data['tokenized_review'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])

In [26]:
data['lemmatized_review'][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'review',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bang',
 'door',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [27]:
# Preparing our text in right format
# Right now, each row in the 'lemmatized_token' column contains a seperate list of tokens
# Each review is stored as its own list of lemmatized words
# We need to combine these smaller lists into one longer list that contains every token from all reviews

tokens_clean = sum(data['lemmatized_review'], [])

In [28]:
tokens_clean

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'review',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bang',
 'door',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night',
 'ok',
 'nothing',
 'special',
 'charge',
 'diamond',
 'member',
 'hilton',
 'decided',
 'chain',
 'shot',
 '20th',
 'anniversary',
 'seattle',
 'start',
 'booked',
 'suite',
 'paid',
 'extra',
 'website',
 'description',
 'not',
 'suite',
 'bedroom',
 'bathroom',
 'standard',
 'hotel',
 'room',
 'took',
 'printed',
 'reservation',
 'desk',
 'showed',
 'said',
 'thing',
 'like',
 'tv',
 'couch',
 'ect',
 'desk',
 'clerk',
 'told',
 'oh',
 'mixed',
 'suite',
 'description',
 'kimpton',
 'website',
 'sorry',
 'free',
 'breakfast',
 'got',
 'kidding',
 'embassy',
 'suit',
 'sitting',
 'room',
 'bathroom',
 'bedroom',
 'unlike',
 'kimpton',
 'call',
 'suite',
 '5',
 'day',
 'stay',
 'offer',
 'correct',
 'false',
 'advertising',
 'send',
 'kimpton',
 'preferred',
 'guest',
 'website',
 'email',
 'asking',
 'failure',
 'provide',
 'suite',
 'advertised',
 'website',
 'reservation',
 'description',
 'furnished',
 'hard',
 'copy',
 'reservation',
 'printout',
 'website',
 'desk',
 'manager',
 'duty',
 'not',
 'reply',
 'solution',
 'send',
 'email',
 'trip',
 'guest',
 'survey',
 'not',
 'follow',
 'email',
 'mail',
 'guess',
 'tell',
 'concerned',
 'guestthe',
 'staff',
 'ranged',
 'indifferent',
 'not',
 'helpful',
 'asked',
 'desk',
 'good',
 'breakfast',
 'spot',
 'neighborhood',
 'hood',
 'told',
 'hotel',
 'gee',
 'best',
 'breakfast',
 'spot',
 'seattle',
 '12',
 'block',
 'away',
 'convenient',
 'hotel',
 'not',
 'know',
 'exist',
 'arrived',
 'late',
 'night',
 '11',
 'pm',
 'inside',
 'run',
 'bellman',
 'busy',
 'chating',
 'cell',
 'phone',
 'help',
 'bagsprior',
 'arrival',
 'emailed',
 'hotel',
 'inform',
 '20th',
 'anniversary',
 'half',
 'really',
 'picky',
 'wanted',
 'make',
 'sure',
 'good',
 'got',
 'nice',
 'email',
 'saying',
 'like',
 'deliver',
 'bottle',
 'champagne',
 'chocolate',
 'covered',
 'strawberry',
 'room',
 'arrival',
 'celebrate',
 'told',
 'needed',
 'foam',
 'pillow',
 'arrival',
 'champagne',
 'strawberry',
 'foam',
 'pillow',
 'great',
 'room',
 'view',
 'alley',
 'high',
 'rise',
 'building',
 'good',
 'not',
 'better',
 'housekeeping',
 'staff',
 'cleaner',
 'room',
 'property',
 'impressed',
 'left',
 'morning',
 'shopping',
 'room',
 'got',
 'short',
 'trip',
 '2',
 'hour',
 'bed',
 'comfortablenot',
 'good',
 'acheat',
 'control',
 '4',
 'x',
 '4',
 'inch',
 'screen',
 'bring',
 'green',
 'shine',
 'directly',
 'eye',
 'night',
 'light',
 'sensitive',
 'tape',
 'controlsthis',
 'not',
 '4',
 'start',
 'hotel',
 'clean',
 'business',
 'hotel',
 'super',
 'high',
 'rate',
 'better',
 'chain',
 'hotel',
 'seattle',
 'nice',
 'room',
 'not',
 '4',
 'star',
 'experience',
 'hotel',
 'monaco',
 'seattle',
 'good',
 'hotel',
 'nt',
 '4',
 'star',
 'levelpositives',
 'large',
 'bathroom',
 'mediterranean',
 'suite',
 'comfortable',
 'bed',
 'pillowsattentive',
 'housekeeping',
 'staffnegatives',
 'ac',
 'unit',
 'malfunctioned',
 'stay',
 'desk',
 'disorganized',
 'missed',
 '3',
 'separate',
 'wakeup',
 'call',
 'concierge',
 'busy',
 'hard',
 'touch',
 'nt',
 'provide',
 'guidance',
 'special',
 'requeststv',
 'hard',
 'use',
 'ipod',
 'sound',
 'dock',
 'suite',
 'non',
 'functioning',
 'decided',
 'book',
 'mediterranean',
 'suite',
 '3',
 'night',
 'weekend',
 'stay',
 '1st',
 'choice',
 'rest',
 'party',
 'filled',
 'comparison',
 'w',
 'spent',
 '45',
 'night',
 'larger',
 'square',
 'footage',
 'room',
 'great',
 'soaking',
 'tub',
 'whirlpool',
 'jet',
 'nice',
 'showerbefore',
 'stay',
 'hotel',
 'arrange',
 'car',
 'service',
 'price',
 '53',
 'tip',
 'reasonable',
 'driver',
 'waiting',
 'arrivalcheckin',
 'easy',
 'downside',
 'room',
 'picked',
 '2',
 'person',
 'jacuzi',
 'tub',
 'bath',
 'accessory',
 'salt',
 'bubble',
 'bath',
 'nt',
 'stay',
 'night',
 'got',
 '121a',
 'checked',
 'voucher',
 'bottle',
 'champagne',
 'nice',
 'gesture',
 'fish',
 'waiting',
 'room',
 'impression',
 'room',
 'huge',
 'open',
 'space',
 'felt',
 'room',
 'big',
 'tv',
 'far',
 'away',
 'bed',
 'chore',
 'change',
 'channel',
 'ipod',
 'dock',
 'broken',
 'disappointingin',
 'morning',
 'way',
 'asked',
 'desk',
 'check',
 'thermostat',
 'said',
 '65f',
 '74',
 '2',
 'degree',
 'warm',
 'try',
 'cover',
 'face',
 'night',
 'bright',
 'blue',
 'light',
 'kept',
 'got',
 'room',
 'night',
 'no',
 '1st',
 'drop',
 'desk',
 'called',
 'maintainence',
 'came',
 'look',
 'thermostat',
 'told',
 'play',
 'setting',
 'happy',
 'digital',
 'box',
 'wo',
 'nt',
 'work',
 'asked',
 'wakeup',
 '10am',
 'morning',
 'nt',
 'happen',
 'called',
 'later',
 '6pm',
 'nap',
 'wakeup',
 'forgot',
 '10am',
 'wakeup',
 'morning',
 'yep',
 'forgottenthe',
 'bathroom',
 'facility',
 'great',
 'room',
 'surprised',
 'room',
 'sold',
 'whirlpool',
 'bath',
 'tub',
 'nt',
 'bath',
 'amenity',
 'great',
 'relax',
 'water',
 'jet',
 'going',
 'unique',
 'great',
 'stay',
 'wonderful',
 'time',
 'hotel',
 'monaco',
 'location',
 'excellent',
 'short',
 'stroll',
 'main',
 'downtown',
 'shopping',
 'area',
 'pet',
 'friendly',
 'room',
 'showed',
 'sign',
 'animal',
 'hair',
 'smell',
 'monaco',
 'suite',
 'sleeping',
 'area',
 'big',
 'striped',
 'curtain',
 'pulled',
 'closed',
 'nice',
 'touch',
 'felt',
 'cosy',
 'goldfish',
 'named',
 'brandi',
 'enjoyed',
 'nt',
 'partake',
 'free',
 'wine',
 'coffeetea',
 'service',
 'lobby',
 'thought',
 'great',
 'feature',
 'great',
 'staff',
 'friendly',
 'free',
 'wireless',
 'internet',
 'hotel',
 'worked',
 'suite',
 '2',
 'laptop',
 'decor',
 'lovely',
 'eclectic',
 'mix',
 'patten',
 'color',
 'palatte',
 'animal',
 'print',
 'bathrobe',
 'feel',
 'like',
 'rock',
 'star',
 'nice',
 'nt',
 'look',
 'like',
 'sterile',
 'chain',
 'hotel',
 'hotel',
 'personality',
 'excellent',
 'stay',
 'great',
 'stay',
 'great',
 'stay',
 'went',
 'seahawk',
 'game',
 'awesome',
 'downfall',
 'view',
 'building',
 'nt',
 'complain',
 'room',
 'huge',
 'staff',
 'helpful',
 'booked',
 'hotel',
 'website',
 'seahawk',
 'package',
 'charge',
 'parking',
 'got',
 'voucher',
 'taxi',
 'problem',
 'taxi',
 'driver',
 'nt',
 'want',
 'accept',
 'voucher',
 'barely',
 'spoke',
 'english',
 'funny',
 'thing',
 'speak',
 'arabic',
 'called',
 'started',
 'making',
 'comment',
 'girlfriend',
 'cell',
 'phone',
 'buddy',
 'took',
 'second',
 'realize',
 'said',
 'fact',
 'speak',
 'language',
 'face',
 'priceless',
 'as',
 'told',
 'said',
 'large',
 'city',
 'told',
 'head',
 'doorman',
 'issue',
 'called',
 'cab',
 'company',
 'promply',
 'answer',
 'nt',
 'apologized',
 'offered',
 'pay',
 'taxi',
 'buck',
 '2',
 'mile',
 'stadium',
 'game',
 'plan',
 'taxi',
 'return',
 'going',
 'humpin',
 'great',
 'walk',
 'nt',
 'mind',
 'right',
 'christmas',
 'wonderful',
 'light',
 'homeless',
 'stowed',
 'away',
 'building',
 'entrance',
 'leave',
 'police',
 'presence',
 'not',
 'greatest',
 'area',
 'stadium',
 'activity',
 '7',
 'block',
 'pike',
 'street',
 'waterfront',
 'great',
 'coffee',
 'shop',
 'way',
 'hotel',
 'mantained',
 'foyer',
 'awesome',
 'wine',
 'tasting',
 'available',
 'evening',
 'best',
 'dog',
 'taking',
 'st',
 'bernard',
 'time',
 'family',
 'safe',
 'hotel',
 'located',
 'service',
 'desk',
 'room',
 'bathroom',
 'huge',
 'jetted',
 'tub',
 'huge',
 'funny',
 'house',
 'keeping',
 'walked',
 'girlfriend',
 'getting',
 'dressed',
 'nt',
 'hear',
 'knock',
 'turn',
 'service',
 'screamed',
 'girlfriend',
 'scream',
 'hit',
 'floor',
 'laughing',
 'started',
 'talking',
 'spanish',
 'worked',
 'place',
 'recommend',
 'price',
 'check',
 'online',
 'deal',
 'good',
 'not',
 'better',
 'besite',
 'contains',
 'deal',
 'voucher',
 'travel',
 'website',
 'nt',
 'tell',
 'love',
 'monaco',
 'staff',
 'husband',
 'stayed',
 'hotel',
 'crazy',
 'weekend',
 'attending',
 'memorial',
 'service',
 'best',
 'friend',
 'husband',
 'celebrating',
 '12th',
 'wedding',
 'anniversary',
 'talk',
 'mixed',
 'emotion',
 'booked',
 'suite',
 'hotel',
 'monte',
 'carlos',
 'loaned',
 'beautiful',
 'fantanned',
 'goldfish',
 'named',
 'joliet',
 'weekend',
 'visited',
 'dog',
 'worked',
 'desk',
 'human',
 'companion',
 'room',
 'decorated',
 'nicely',
 'couch',
 'used',
 'pillow',
 'loccitane',
 'bath',
 'amenity',
 'welcome',
 'sight',
 'room',
 'quiet',
 'peaceful',
 'wireless',
 'internet',
 'access',
 'wonderful',
 'server',
 'went',
 'morning',
 'leaving',
 'problem',
 'printing',
 'boarding',
 'pass',
 'afternoon',
 'reception',
 'serf',
 'oenophilesatisfying',
 'wine',
 'australia',
 'scrumptious',
 'cooky',
 'restaurant',
 'closed',
 'renovation',
 'stay',
 'finally',
 'ate',
 'food',
 'good',
 'drink',
 'better',
 'word',
 'caution',
 'restaurant',
 'larger',
 'person',
 'not',
 'sit',
 'booth',
 'wo',
 'nt',
 'fit',
 '56',
 '125',
 'lb',
 'husband',
 '59',
 '175',
 'table',
 'smackagainst',
 'stomach',
 'couple',
 'inch',
 'space',
 'mighty',
 'uncomfortable',
 'patron',
 'larger',
 'pregnant',
 'bad',
 'design',
 'opinion',
 'place',
 'decorated',
 'funky',
 'welcoming',
 'way',
 'metal',
 'wood',
 'handblown',
 'glass',
 'light',
 'fixture',
 'expect',
 'seattle',
 'capital',
 'glass',
 'art',
 'industry',
 'definitely',
 'stay',
 'reason',
 'cozy',
 'stay',
 'rainy',
 'city',
 'husband',
 'spent',
 '7',
 'night',
 'monaco',
 'early',
 'january',
 '2008',
 'business',
 'trip',
 'chance',
 'come',
 'ridewe',
 'booked',
 'monte',
 'carlo',
 'suite',
 'proved',
 'comfortable',
 'longish',
 'stay',
 'room',
 '905',
 'located',
 'street',
 'building',
 'street',
 'noise',
 'not',
 'problem',
 'view',
 'interesting',
 'room',
 'building',
 'look',
 'dank',
 'alley',
 'midsection',
 'large',
 'office',
 'building',
 'suite',
 'comfortable',
 'plenty',
 'room',
 'spread',
 'bathroom',
 'attractive',
 'squeaky',
 'clean',
 'small',
 'comparison',
 ...]

In [29]:
unigrams = pd.Series(nltk.ngrams(tokens_clean, 1)).value_counts()

In [30]:
unigrams

(hotel,)         292
(room,)          275
(great,)         126
(not,)           122
(stay,)           95
                ...
(touring,)         1
(asia,)            1
(maintained,)      1
(slipper,)         1
(connected,)       1
Name: count, Length: 2588, dtype: int64

In [31]:
bigrams = pd.Series(nltk.ngrams(tokens_clean, 2)).value_counts()

In [32]:
bigrams

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(staff, friendly)     12
(pike, place)         12
                      ..
(huge, mall)           1
(mall, hotel)          1
(hotel, connected)     1
(connected, good)      1
(food, raffle)         1
Name: count, Length: 8263, dtype: int64