# Converting text to lowercase

## using .lower() method

In [3]:
sentence = "This is a Test Sentence"

In [4]:
lower_sentence = sentence.lower()
print(lower_sentence)

this is a test sentence

In [5]:
sentence_list = ["This is Sentence 1",
                 "This is Sentence 2",
                 "This is Sentence 3"]

In [6]:
lowercased_sentence_list = [sentence.lower() for sentence in sentence_list]
print(lowercased_sentence_list)

['this is sentence 1', 'this is sentence 2', 'this is sentence 3']

# Removing Stopwords

## eg: "and", "of", "a","to"

## NLTK - Natural Language Toolkit

1. Predefined lists of stopwords
2. Tools for tokenizing text
3. Datasets for experiments

In [1]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vaidheeshk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [3]:
from nltk.corpus import stopwords

In [4]:
en_stopwords = stopwords.words("english")

In [5]:
print(en_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [9]:
sentence = "It was too far to go to the shop and he did not want her to walk"

In [10]:
sentence_with_no_stopwords = " ".join([word for word in sentence.split() if word not in en_stopwords])

In [12]:
print(sentence_with_no_stopwords)

It far go shop want walk

In [13]:
en_stopwords.append("It")

In [14]:
sentence_with_no_stopwords = " ".join([word for word in sentence.split() if word not in en_stopwords])

In [15]:
print(sentence_with_no_stopwords)

far go shop want walk

# Regular Expressions

A special way of writing patterns to search through text

The `r` character indicates that the text is a raw string

In [16]:
import re

In [18]:
folder_path = r"C:\desktop\notes"
print(folder_path)

C:\desktop\notes

In [21]:
result = re.search("pattern", r"string to contain the pattern") # checks whether a specified patterns appears within a string

In [22]:
print(result)

<re.Match object; span=(22, 29), match='pattern'>

In [23]:
string = r'sara was able to find the items rather quickly'

new_string = re.sub("sara", "sarah", string) # searches for a specific text within a string and replaces it with new content
print(new_string)

sarah was able to find the items rather quickly

`^` - start of the string,<br>
`$` - end of the string,<br>
`|` - works like a `or`

## Removing punctuations

pattern = r"[^\w\s]"

`[]` - a set of characters we want to match<br>
`^` - not<br>
`\w` - word characters<br>
`\s` - whitespaces

find anything that is not a word character or a white space

# Tokenization

Breaking text into smaller tokens.<br>It is easier for analysis

'punkt_tab': a table used to figure out where sentences begin and end

In [24]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize, sent_tokenize

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vaidheeshk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

In [25]:
sentences = "Her cat's name is Luna. Her dog's name is Max"

In [26]:
sent_tokenize(sentences)

["Her cat's name is Luna.", "Her dog's name is Max"]

In [27]:
sentence_1 = "Her cat's name is Luna and her dog's name is Max"

In [28]:
word_tokenize(sentence_1)

['Her',
 'cat',
 "'s",
 'name',
 'is',
 'Luna',
 'and',
 'her',
 'dog',
 "'s",
 'name',
 'is',
 'Max']

# Stemming

Words are reduced to their base form.<br>It reduces the number of unique words.

1. Reduces complexity
2. Keeps the dataset easier to manage

Drawbacks: Output is not always meaningful

In [29]:
from nltk.stem import PorterStemmer

In [30]:
ps = PorterStemmer()

In [31]:
connect_tokens = ["connecting", "connectivity", "connected", "connector", "connect"]

In [32]:
for token in connect_tokens:
    print(token, ": ", ps.stem(token))

connecting :  connect
connectivity :  connect
connected :  connect
connector :  connector
connect :  connect

# Lemmatization

It reduces a word to a meaningful base form while preserving its intended meaning.<br>It uses a predefined dictionary to keep the context of the word

Drawback: we may still have more unique words in our dataset compared to stemming

In [34]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\vaidheeshk\AppData\Roaming\nltk_data...

True

In [35]:
from nltk.stem import WordNetLemmatizer

In [36]:
lm = WordNetLemmatizer()

In [37]:
for token in connect_tokens:
    print(token, ": ", lm.lemmatize(token))

connecting :  connecting
connectivity :  connectivity
connected :  connected
connector :  connector
connect :  connect

When preprocessing text , it is always worth making a new column 
for each of the steps in your preprocessing

In Python, when we use sum() with lists instead of numberm it joins them together

# Text Tagging

1. Parts of Speech (POS)
2. Named Entity Recognition (NER)

POS Tagging:

labeling each word in a sentence with its grammatical role
(eg: NOUN, VERB, ADJ)

## POS tagging

spaCy: An NLP library that comes with pretrained models capable of recognizing
parts of speech, named entities and other linguistic features

In [1]:
import spacy
import pandas as pd

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
text = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(text)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

A spacy document: an object that stored all the text along with all the linguistic 
information spacy generates

In [4]:
spacy_doc = nlp(text)

In [5]:
pos_df = pd.DataFrame(columns=["token", "pos_tag"])

In [6]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df,
                        pd.DataFrame.from_records([{"token": token.text, 
                                                    "pos_tag": token.pos_}])],
                       ignore_index=True)

In [7]:
pos_df.head(10)

         token pos_tag
0         emma   PROPN
1    woodhouse   PROPN
2     handsome     ADJ
3       clever     ADJ
4          and   CCONJ
5         rich     ADJ
6         with     ADP
7            a     DET
8  comfortable     ADJ
9         home    NOUN

In [8]:
pos_df_count = pos_df.groupby(["token", "pos_tag"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)

In [10]:
pos_df_count.head(10)

    token pos_tag  counts
88     of     ADP      14
54    her    PRON       9
49    had     AUX       9
6     and   CCONJ       8
111   the     DET       8
0       a     DET       6
114    to    PART       5
61     in     ADP       4
120  very     ADV       4
13   been     AUX       4

In [11]:
pos_df_pos_tag_count = pos_df_count.groupby(["pos_tag"])["token"].count().sort_values(ascending=False)

In [12]:
pos_df_pos_tag_count.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [16]:
nouns = pos_df_count[pos_df_count["pos_tag"] == "NOUN"][:10]
print(nouns)

         token pos_tag  counts
48   governess    NOUN       3
46      friend    NOUN       3
130      years    NOUN       2
28   daughters    NOUN       2
35        emma    NOUN       2
82      mother    NOUN       2
103    sisters    NOUN       2
1    affection    NOUN       1
11   authority    NOUN       1
32    distress    NOUN       1

## Named Entity Recognition

finding and labeling essential pieces of information in text.
NER uses a combination of rules and machine learning to discover the entities

In [17]:
import spacy
from spacy import displacy
from spacy import tokenizer
from IPython.display import HTML, display

In [18]:
nlp = spacy.load('en_core_web_sm')

In [19]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
print(google_text)

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [20]:
spacy_doc = nlp(google_text)

In [21]:
for word in spacy_doc.ents:
    print(word.text, word.label_)
# .label: a numeric ID of the entity
# .label_: a human-readable label

Google ORG
September 4, 1998 DATE
Larry Page PERSON
Sergey Brin PERSON
PhD WORK_OF_ART
Stanford University ORG
California GPE
about 14% PERCENT
56% PERCENT
IPO ORG
2004 DATE
2015 DATE
Google ORG
Alphabet Inc. ORG
Alphabet ORG
Alphabet ORG
Sundar Pichai PERSON
Google ORG
October 24, 2015 DATE
Larry Page PERSON
Alphabet GPE
December 3, 2019 DATE
Pichai PERSON
Alphabet GPE

In [22]:
html = displacy.render(spacy_doc, style="ent", jupyter=False)
display(HTML(html))

In [24]:
import re

In [25]:
google_text_clean = re.sub(r'[^\w\s]', '', google_text).lower()
print(google_text_clean)

google was founded on september 4 1998 by computer scientists larry page and sergey brin while they were phd students at stanford university in california together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet

In [26]:
clean_spacy_doc = nlp(google_text_clean)

In [27]:
for word in clean_spacy_doc.ents:
    print(word.text, word.label_)

google ORG
september 4 1998 DATE
stanford university ORG
california GPE
about 14 CARDINAL
56 CARDINAL
2004 DATE
2015 DATE
alphabet inc google ORG
google ORG
october 24 2015 DATE
larry PERSON
december 3 2019 DATE

In [28]:
html = displacy.render(clean_spacy_doc, style="ent", jupyter=False)
display(HTML(html))